config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
    has_many :bookmarks, dependent: :destroy
    has_many :movies, through: :bookmarks
    validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :bookmarks
    #has_many :lists, through: :bookmarks
    validates :title, uniqueness: true, presence: true
    validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
    def new
        @list = List.find(params[:list_id])
        @bookmark = Bookmark.new
    end
    def create
        @bookmark = Bookmark.new(bookmark_params)
        @list = List.find(params[:list_id])
        @bookmark.list = @list
        if @bookmark.save
          redirect_to list_path(@list)
        else
          render :new
        end
    end
    def destroy
        @bookmark = Bookmark.find(params[:id])
        @bookmark.destroy
        redirect_to list_path(@bookmark.list)
    end

    private

    def bookmark_params
        params.require(:bookmark).permit(:comment, :movie_id)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    def index
        @lists = List.all
    end
    def show
        @list = List.find(params[:id])
    end
    def new
        @list = List.new
    end
    def create
        @list = List.new(list_params)
        if @list.save
          redirect_to list_path(@list)
        else
          render :new
        end
    end

    private

    def list_params
        params.require(:list).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://sm.ign.com/t/ign_es/category/m/movies/movies_rpue.1200.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "My lists", lists_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "add list", new_list_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%# <%= link_to "Action", "#", class: "dropdown-item" %>
              <%# <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%#= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>

<div class="home-banner">
  <h1>Save any kind of movie</h1>
</div>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-12">
      <div class="d-flex justify-content-between">
        <div><h2>My lists</h2></div>
        <div><button type="button" class="btn btn-warning rounded-pill"><%= link_to 'agregar una lista', new_list_path, class: "text-white text-decoration-none"%></button></div>
      </div>
      <div>
        <% @lists.each do |e| %>
            <div class="card-list">
                <h2><%= link_to e.name, list_path(e) %></h2>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<%= render "form", list: @list %>

app/views/lists/show.html.erb
<%= @list.name %>
<%= link_to 'mostrar todas las listas', lists_path %>
<%= link_to 'add a bookmark', new_list_bookmark_path(@list) %>


<% @list.movies.each do |movie|%>
<div>
    <% bookmark = Bookmark.find_by(list: @list, movie: movie)%>
    <%= bookmark.comment%>
    <%= movie.title%>
    <%= link_to "Delete el listado",
            bookmark_path(bookmark),
            method: :delete,
            data: { confirm: "Are you sure?" } %>  
</div>
<%end%>